# Generated by Django 4.2.4 on 2023-08-26 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recepie',
            new_name='Recipe',
        ),
    ]
